### PR TITLE
Pass changed file as template parameter to watchers

### PR DESCRIPTION
**Pull request by artsparkAI**
This change makes it so that the watcher command can be passed the changed file path as an argument. This is very useful for running tests without having to re-run the entire suite. It's especially useful for fast iteration when used in conjunction with single test isolation such as `it.only`.

### Changed file as argument

The path of the changed file can be inserted into positional arguments using the template parameter `{path}`. This speeds up iteration in testing, especially if using single test isolation (for example, by using `it.only("test")` in mocha.)

Example:
````
module.exports = {
  watcher: {
    test: {
      tasks: [{ command: 'test', params: { testFiles: ['{path}'] } }],
      files: ['./test/**/*'],
      verbose: true
    }
  }
}
````

### CODE REVIEW

**Comment by xanderdeseyn** [comment]
Hi, this looks good, thanks for the PR! Is there a reason you removed the dist folder from gitignore?

If possible, please add dist back and remove the build files from the PR, then I will merge :)

**Comment by artsparkAI** [comment]
Oh sorry I will fix that. That was just a temporary hack for myself so I could point to github directly rather than having to go through NPM publish/install cycle.

**Comment by artsparkAI** [comment]
@N1ghtly Okay done

**Comment by xanderdeseyn** [comment]
Merged, thank you for the contribution!

**Pull request merged**
